ucf101: 101 classes
Method : OURS
----AGE 5----
current_task  [89, 0, 61, 1, 92, 94, 64, 71, 87, 51]
current_head  101
Phase 2 : Train RGB Model in an Incremental Manner
=> base model: resnet34
----------------------resnet34 pretraining----------------------
------------------------------success---------------------------
Load the Previous Model
Copy the old Model
lambda_0  : [1.0, 0.030166206257996712]
Increment the Model
SplitCosineLinear(
  input_features=512, output_features=303, sigma=tensor([3.9528]), eta=tensor([3.2879])
  (fc1): CosineLinear(input_features=512, output_features=273, sigma=1.0, eta=1.0)
  (fc2): CosineLinear(input_features=512, output_features=30, sigma=1.0, eta=1.0)
)
video number : 944
video number + exemplar : 1399
DataLoader Constructed : Train 43
Optimizer Constructed
video number : 944
video number + exemplar : 944
Initialize Cosine Classifier
Computing the class mean vectors...
Traceback (most recent call last):
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
Traceback (most recent call last):
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/ustc/anaconda3/envs/lhc/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main()
  File "main.py", line 71, in main
    train_i_cl.train_task(args, i, current_task, current_head, class_indexer, model_flow=model_flow, prefix=prefix)
  File "/home/ustc/ls/tcd_code/train/train_i_cl.py", line 467, in train_task
    cl_utils.init_cosine_classifier(model,current_task,class_indexer,loader_for_embedding,args)
  File "/home/ustc/ls/tcd_code/cl_methods/cl_utils.py", line 112, in init_cosine_classifier
    cls_embedding, features = compute_class_mean(model,current_task,dloader,class_indexer)
  File "/home/ustc/ls/tcd_code/cl_methods/classifer.py", line 53, in compute_class_mean
    feat = outputs['feat'].data.cpu()
KeyboardInterrupt